export { HomePage } from "./HomePage"
export { AboutPage } from "./AboutPage"
export { CollectionPage } from "./CollectionPage"
export { ContactPage } from "./ContactPage"
export { MenuPage } from "./MenuPage"
export { NewPage } from "./NewPage"
export { NewDetailPage } from "./NewDetailPage"
export { ReservationInfoPage } from "./ReservationInfoPage"

export { ProfilePage } from "./ProfilePage"
export { VoucherPage } from "./VoucherPage"
export { BillPage } from "./BillPage"
export { BookTablePage } from "./BookTablePage"
export { TableCanceledPage } from "./TableCanceledPage"
export { TableCanceledDetailPage } from "./TableCanceledDetailPage"
export { TableBookedPage } from "./TableBookedPage"
export { TableBookedDetailPage } from "./TableBookedDetailPage"
export { OrderFoodPage } from "./OrderFoodPage"
